### ISSUE TITLE
When I click "Generate Invite Link" under Settings, an invite link directs me to a login page (and not a signup page)

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#347] opened 2020-12-18 21:29 UTC
When logged in as an admin, and I am under the settings page, and I already have a user in the system who hasnt yet accepted the invite, if I click "Generate Invite Link", a link is generated, but when the user clicks on it, it takes them to a sign in page and not a sign up page (example, I invited blockchain@unicef.org, and the below link is what is generated when I click "Generate Invite Link"

https://juniper.unicef.io/admin/signin?verification=6346516326072727008405522480712246

![image](https://user-images.githubusercontent.com/49003323/102663005-f4c88000-414d-11eb-8f0e-33de6fc7e980.png)

**Comment by mehranhydary** [comment] 2020-12-22 17:05
Hola - the reason that this occurred is because the link generated was for juniper.unicef.io instead of juniper-staging.unicef.io (the site you were actually using). If you update the URL to https://juniper-staging.unicef.io/admin/signin?verification=6346516326072727008405522480712246 it works as intended.

Closing for now! Please re-open if you don't see this page: 
![Screen Shot 2020-12-22 at 12 04 53 PM](https://user-images.githubusercontent.com/2007405/102914214-edef8500-444d-11eb-8b3d-b6bd96e1fc69.png)

**Closed by mehranhydary** 2020-12-22 17:05 UTC
